### ISSUE TITLE
UI/UX Cleanup

### ISSUE THREAD

**Issue by VijayP30** [StephenTan12/Horoscope-Team-5#4]
Potential Changes:
- [x] #29 
- [x] Fix inconsistencies in font
- [x] Potentially make background more animated (currently the only animation is from a new horoscope)

**Comment by xis004** [comment]
- [ ] Optimize birthday slider, easier navigation and restrict dates (currently dates back to 1800s and also future dates).

**Comment by VijayP30** [comment]
requires:
- [ ] #42
